sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t hsm0156/docker-react-app -f Dockerfile .

script: 
  - docker run -e CI=true hsm0156/docker-react-app npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-react-app
  env: Dockerreactapp-env
  bucket_name: elasticbeanstalk-us-west-2-042489425414
  bucket_path: docker-react-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
